//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.04 at 12:37:11 AM CEST 
//


package com.app.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Deo" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.parlament.gov.rs/Acti}Glava" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="naziv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Podaci_o_glasanju">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Broj_glasova_za" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Broj_glasova_uzdrzan" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Broj_glasova_protiv" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Podaci_o_razresenju_statusa">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Datum_prihvatanja_u_nacelu" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="Datum_prihvatanja_u_pojedinostima" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="Datum_prihvatanja_u_celosti" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="naziv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="predlagac" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deo",
    "podaciOGlasanju",
    "podaciORazresenjuStatusa"
})
@XmlRootElement(name = "Akt")
public class Act {

    @XmlElement(name = "Deo", required = true)
    protected List<Act.Deo> deo;
    @XmlElement(name = "Podaci_o_glasanju", required = true)
    protected Act.PodaciOGlasanju podaciOGlasanju;
    @XmlElement(name = "Podaci_o_razresenju_statusa", required = true)
    protected Act.PodaciORazresenjuStatusa podaciORazresenjuStatusa;
    @XmlAttribute(name = "naziv")
    protected String naziv;
    @XmlAttribute(name = "status", required = true)
    protected String status;
    @XmlAttribute(name = "predlagac", required = true)
    protected String predlagac;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the deo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Act.Deo }
     * 
     * 
     */
    public List<Act.Deo> getDeo() {
        if (deo == null) {
            deo = new ArrayList<Act.Deo>();
        }
        return this.deo;
    }

    /**
     * Gets the value of the podaciOGlasanju property.
     * 
     * @return
     *     possible object is
     *     {@link Act.PodaciOGlasanju }
     *     
     */
    public Act.PodaciOGlasanju getPodaciOGlasanju() {
        return podaciOGlasanju;
    }

    /**
     * Sets the value of the podaciOGlasanju property.
     * 
     * @param value
     *     allowed object is
     *     {@link Act.PodaciOGlasanju }
     *     
     */
    public void setPodaciOGlasanju(Act.PodaciOGlasanju value) {
        this.podaciOGlasanju = value;
    }

    /**
     * Gets the value of the podaciORazresenjuStatusa property.
     * 
     * @return
     *     possible object is
     *     {@link Act.PodaciORazresenjuStatusa }
     *     
     */
    public Act.PodaciORazresenjuStatusa getPodaciORazresenjuStatusa() {
        return podaciORazresenjuStatusa;
    }

    /**
     * Sets the value of the podaciORazresenjuStatusa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Act.PodaciORazresenjuStatusa }
     *     
     */
    public void setPodaciORazresenjuStatusa(Act.PodaciORazresenjuStatusa value) {
        this.podaciORazresenjuStatusa = value;
    }

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the predlagac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredlagac() {
        return predlagac;
    }

    /**
     * Sets the value of the predlagac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredlagac(String value) {
        this.predlagac = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.parlament.gov.rs/Acti}Glava" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="naziv" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "glava"
    })
    public static class Deo {

        @XmlElement(name = "Glava", required = true)
        protected List<Glava> glava;
        @XmlAttribute(name = "naziv")
        protected String naziv;
        @XmlAttribute(name = "id")
        protected String id;

        /**
         * Gets the value of the glava property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the glava property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGlava().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Glava }
         * 
         * 
         */
        public List<Glava> getGlava() {
            if (glava == null) {
                glava = new ArrayList<Glava>();
            }
            return this.glava;
        }

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Broj_glasova_za" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Broj_glasova_uzdrzan" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Broj_glasova_protiv" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojGlasovaZa",
        "brojGlasovaUzdrzan",
        "brojGlasovaProtiv"
    })
    public static class PodaciOGlasanju {

        @XmlElement(name = "Broj_glasova_za", defaultValue = "0")
        protected Integer brojGlasovaZa;
        @XmlElement(name = "Broj_glasova_uzdrzan", defaultValue = "0")
        protected Integer brojGlasovaUzdrzan;
        @XmlElement(name = "Broj_glasova_protiv", defaultValue = "0")
        protected Integer brojGlasovaProtiv;

        /**
         * Gets the value of the brojGlasovaZa property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBrojGlasovaZa() {
            return brojGlasovaZa;
        }

        /**
         * Sets the value of the brojGlasovaZa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBrojGlasovaZa(Integer value) {
            this.brojGlasovaZa = value;
        }

        /**
         * Gets the value of the brojGlasovaUzdrzan property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBrojGlasovaUzdrzan() {
            return brojGlasovaUzdrzan;
        }

        /**
         * Sets the value of the brojGlasovaUzdrzan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBrojGlasovaUzdrzan(Integer value) {
            this.brojGlasovaUzdrzan = value;
        }

        /**
         * Gets the value of the brojGlasovaProtiv property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBrojGlasovaProtiv() {
            return brojGlasovaProtiv;
        }

        /**
         * Sets the value of the brojGlasovaProtiv property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBrojGlasovaProtiv(Integer value) {
            this.brojGlasovaProtiv = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Datum_prihvatanja_u_nacelu" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="Datum_prihvatanja_u_pojedinostima" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="Datum_prihvatanja_u_celosti" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datumPrihvatanjaUNacelu",
        "datumPrihvatanjaUPojedinostima",
        "datumPrihvatanjaUCelosti"
    })
    public static class PodaciORazresenjuStatusa {

        @XmlElement(name = "Datum_prihvatanja_u_nacelu")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPrihvatanjaUNacelu;
        @XmlElement(name = "Datum_prihvatanja_u_pojedinostima")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPrihvatanjaUPojedinostima;
        @XmlElement(name = "Datum_prihvatanja_u_celosti")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPrihvatanjaUCelosti;

        /**
         * Gets the value of the datumPrihvatanjaUNacelu property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPrihvatanjaUNacelu() {
            return datumPrihvatanjaUNacelu;
        }

        /**
         * Sets the value of the datumPrihvatanjaUNacelu property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPrihvatanjaUNacelu(XMLGregorianCalendar value) {
            this.datumPrihvatanjaUNacelu = value;
        }

        /**
         * Gets the value of the datumPrihvatanjaUPojedinostima property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPrihvatanjaUPojedinostima() {
            return datumPrihvatanjaUPojedinostima;
        }

        /**
         * Sets the value of the datumPrihvatanjaUPojedinostima property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPrihvatanjaUPojedinostima(XMLGregorianCalendar value) {
            this.datumPrihvatanjaUPojedinostima = value;
        }

        /**
         * Gets the value of the datumPrihvatanjaUCelosti property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPrihvatanjaUCelosti() {
            return datumPrihvatanjaUCelosti;
        }

        /**
         * Sets the value of the datumPrihvatanjaUCelosti property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPrihvatanjaUCelosti(XMLGregorianCalendar value) {
            this.datumPrihvatanjaUCelosti = value;
        }

    }

}