//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.04 at 12:37:11 AM CEST 
//


package com.app.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.gov.parlament.akti package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _ClanStavTacka_QNAME = new QName("http://www.parlament.gov.rs/akti", "Tacka");
    private final static QName _ClanStavTackaPodtackaAlineja_QNAME = new QName("http://www.parlament.gov.rs/akti", "Alineja");
    private final static QName _ClanStavTackaPodtacka_QNAME = new QName("http://www.parlament.gov.rs/akti", "Podtacka");
    private final static QName _ClanStav_QNAME = new QName("http://www.parlament.gov.rs/akti", "Stav");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.gov.parlament.akti
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Clan }
     * 
     */
    public Clan createClan() {
        return new Clan();
    }

    /**
     * Create an instance of {@link Act }
     * 
     */
    public Act createAkt() {
        return new Act();
    }

    /**
     * Create an instance of {@link Glava }
     * 
     */
    public Glava createGlava() {
        return new Glava();
    }

    /**
     * Create an instance of {@link Glava.Odeljak }
     * 
     */
    public Glava.Odeljak createGlavaOdeljak() {
        return new Glava.Odeljak();
    }

    /**
     * Create an instance of {@link Clan.Stav }
     * 
     */
    public Clan.Stav createClanStav() {
        return new Clan.Stav();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tacka }
     * 
     */
    public Clan.Stav.Tacka createClanStavTacka() {
        return new Clan.Stav.Tacka();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tacka.Podtacka }
     * 
     */
    public Clan.Stav.Tacka.Podtacka createClanStavTackaPodtacka() {
        return new Clan.Stav.Tacka.Podtacka();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link Act.Deo }
     * 
     */
    public Act.Deo createAktDeo() {
        return new Act.Deo();
    }

    /**
     * Create an instance of {@link Glava.Odeljak.Pododeljak }
     * 
     */
    public Glava.Odeljak.Pododeljak createGlavaOdeljakPododeljak() {
        return new Glava.Odeljak.Pododeljak();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tacka.Podtacka.Alineja }
     * 
     */
    public Clan.Stav.Tacka.Podtacka.Alineja createClanStavTackaPodtackaAlineja() {
        return new Clan.Stav.Tacka.Podtacka.Alineja();
    }	
    

    /**
     * Create an instance of {@link Amendment }
     * 
     */
    public Amendment createAmandman() {
        return new Amendment();
    }

    /**
     * Create an instance of {@link Amendment.ListaPredloga }
     * 
     */
    public Amendment.ListaPredloga createAmandmanListaPredloga() {
        return new Amendment.ListaPredloga();
    }

    /**
     * Create an instance of {@link Amendment.ListaPredloga.PredlogAmandmana }
     * 
     */
    public Amendment.ListaPredloga.PredlogAmandmana createAmandmanListaPredlogaPredlogAmandmana() {
        return new Amendment.ListaPredloga.PredlogAmandmana();
    }

    /**
     * Create an instance of {@link Cvor }
     * 
     */
    public Cvor createCvor() {
        return new Cvor();
    }

    /**
     * Create an instance of {@link Amendment.Obrazlozenje }
     * 
     */
    public Amendment.Obrazlozenje createAmandmanObrazlozenje() {
        return new Amendment.Obrazlozenje();
    }

    /**
     * Create an instance of {@link Amendment.ListaPredloga.PredlogAmandmana.Sadrzaj }
     * 
     */
    public Amendment.ListaPredloga.PredlogAmandmana.Sadrzaj createAmandmanListaPredlogaPredlogAmandmanaSadrzaj() {
        return new Amendment.ListaPredloga.PredlogAmandmana.Sadrzaj();
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Clan.Stav.Tacka }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.parlament.gov.rs/akti", name = "Tacka", scope = Clan.Stav.class)
    public JAXBElement<Clan.Stav.Tacka> createClanStavTacka(Clan.Stav.Tacka value) {
        return new JAXBElement<Clan.Stav.Tacka>(_ClanStavTacka_QNAME, Clan.Stav.Tacka.class, Clan.Stav.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Clan.Stav.Tacka.Podtacka.Alineja }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.parlament.gov.rs/akti", name = "Alineja", scope = Clan.Stav.Tacka.Podtacka.class)
    public JAXBElement<Clan.Stav.Tacka.Podtacka.Alineja> createClanStavTackaPodtackaAlineja(Clan.Stav.Tacka.Podtacka.Alineja value) {
        return new JAXBElement<Clan.Stav.Tacka.Podtacka.Alineja>(_ClanStavTackaPodtackaAlineja_QNAME, Clan.Stav.Tacka.Podtacka.Alineja.class, Clan.Stav.Tacka.Podtacka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Clan.Stav.Tacka.Podtacka }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.parlament.gov.rs/akti", name = "Podtacka", scope = Clan.Stav.Tacka.class)
    public JAXBElement<Clan.Stav.Tacka.Podtacka> createClanStavTackaPodtacka(Clan.Stav.Tacka.Podtacka value) {
        return new JAXBElement<Clan.Stav.Tacka.Podtacka>(_ClanStavTackaPodtacka_QNAME, Clan.Stav.Tacka.Podtacka.class, Clan.Stav.Tacka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Clan.Stav }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.parlament.gov.rs/akti", name = "Stav", scope = Clan.class)
    public JAXBElement<Clan.Stav> createClanStav(Clan.Stav value) {
        return new JAXBElement<Clan.Stav>(_ClanStav_QNAME, Clan.Stav.class, Clan.class, value);
    }

}
