//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 09:51:47 PM CEST 
//


package com.app.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.parlament.gov.rs/akti}ref_attributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "ref")
public class Ref {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "akt")
    @XmlSchemaType(name = "anySimpleType")
    protected String akt;
    @XmlAttribute(name = "deo")
    @XmlSchemaType(name = "anySimpleType")
    protected String deo;
    @XmlAttribute(name = "glava")
    @XmlSchemaType(name = "anySimpleType")
    protected String glava;
    @XmlAttribute(name = "odeljak")
    @XmlSchemaType(name = "anySimpleType")
    protected String odeljak;
    @XmlAttribute(name = "pododeljak")
    @XmlSchemaType(name = "anySimpleType")
    protected String pododeljak;
    @XmlAttribute(name = "clan")
    @XmlSchemaType(name = "anySimpleType")
    protected String clan;
    @XmlAttribute(name = "stav")
    @XmlSchemaType(name = "anySimpleType")
    protected String stav;
    @XmlAttribute(name = "tacka")
    @XmlSchemaType(name = "anySimpleType")
    protected String tacka;
    @XmlAttribute(name = "podtacka")
    @XmlSchemaType(name = "anySimpleType")
    protected String podtacka;
    @XmlAttribute(name = "alineja")
    @XmlSchemaType(name = "anySimpleType")
    protected String alineja;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the akt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAkt() {
        return akt;
    }

    /**
     * Sets the value of the akt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAkt(String value) {
        this.akt = value;
    }

    /**
     * Gets the value of the deo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeo() {
        return deo;
    }

    /**
     * Sets the value of the deo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeo(String value) {
        this.deo = value;
    }

    /**
     * Gets the value of the glava property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlava() {
        return glava;
    }

    /**
     * Sets the value of the glava property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlava(String value) {
        this.glava = value;
    }

    /**
     * Gets the value of the odeljak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdeljak() {
        return odeljak;
    }

    /**
     * Sets the value of the odeljak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdeljak(String value) {
        this.odeljak = value;
    }

    /**
     * Gets the value of the pododeljak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPododeljak() {
        return pododeljak;
    }

    /**
     * Sets the value of the pododeljak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPododeljak(String value) {
        this.pododeljak = value;
    }

    /**
     * Gets the value of the clan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClan() {
        return clan;
    }

    /**
     * Sets the value of the clan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClan(String value) {
        this.clan = value;
    }

    /**
     * Gets the value of the stav property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStav() {
        return stav;
    }

    /**
     * Sets the value of the stav property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStav(String value) {
        this.stav = value;
    }

    /**
     * Gets the value of the tacka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTacka() {
        return tacka;
    }

    /**
     * Sets the value of the tacka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTacka(String value) {
        this.tacka = value;
    }

    /**
     * Gets the value of the podtacka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodtacka() {
        return podtacka;
    }

    /**
     * Sets the value of the podtacka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodtacka(String value) {
        this.podtacka = value;
    }

    /**
     * Gets the value of the alineja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlineja() {
        return alineja;
    }

    /**
     * Sets the value of the alineja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlineja(String value) {
        this.alineja = value;
    }

}
